# Generated by Django 6.0.5 on 2026-06-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "收入"), ("EXPENSE", "支出")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📄", max_length=10, verbose_name="图标"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="金额"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "收入"), ("EXPENSE", "支出")],
                        db_index=True,
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transactions.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "流水",
                "verbose_name_plural": "流水",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
